#!/usr/bin/bash
#
# Put customizations to your image in this file.

MUNSTRAP_VERSION=0.1

# Custom versions and variables
PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

# Configuring image specific packages
echo "* Configuring image specific packages.";


# Cleanup /var/munin in order to set the dataset mountpoint (must be empty)
rm -r /var/munin/*
# Download and extract munstrap to /opt/local/etc/munin/munstrap
echo "* Download and extract munstrap to /opt/local/etc/munin/munstrap"
(mkdir -p /opt/local/etc/munin/munstrap)
curl -L "https://github.com/drscream/munstrap/archive/v${MUNSTRAP_VERSION}.tar.gz" | tar xz -C /opt/local/etc/munin/munstrap --strip-components=1
## rename original template and create symlinks to activate munstrap
(cd /opt/local/etc/munin; mv static static-orig; mv templates templates-orig; ln -s munstrap/static static; ln -s munstrap/templates templates)

# Clean up
echo "* Cleaning up."
rm -rf /root/*

# Prepare image for provisioning
sm-prepare-image -y
